# yaml-language-server: $schema=./config.yml
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/lpmatos
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/lpmatos/
    about: Please report security vulnerabilities here.
