name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Secret Detection
        uses: zricethezav/gitleaks-action@013453f0fab66efcb306749a488e4997e201d05e
        with:
          config-path: ${{ github.workspace }}/.github/config/.gitleaks.toml
        continue-on-error: false

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          config: ${{ github.workspace }}/.github/config/.hadolint.yml
