name: Publish NPM

on:
  workflow_dispatch:
    inputs:
      npm-tag:
        description: NPM Tag
        default: v1.0.0
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install and Push
        run: |
          cd ./code
          npm install
          npm install -g @jsdevtools/npm-publish
          npm-publish --token=${{ secrets.NPM_TOKEN }} package.json
