name: Publish NPM

on:
  workflow_dispatch:
    inputs:
      npm-tag:
        description: NPM Tag
        default: v1.0.0
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: cd ./code && npm install

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.inputs.npm-tag }}
          check-version: true
          package: ./code/package.json

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
