name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      npm-tag:
        description: NPM Tag
        default: 1.0.0
        required: true

jobs:
  npm-publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Get version
        run: |
          echo "VERSION=${{ github.event.inputs.npm-tag }}" >> $GITHUB_ENV

      - name: Install and Push
        run: |
          cd ./code
          npm install
          npm install -g @jsdevtools/npm-publish
          echo "New version is $VERSION"
          npm version $VERSION
          npm-publish --token=${{ secrets.NPM_TOKEN }} package.json
